### ISSUE TITLE
dependencies are not installed

### ISSUE THREAD

**Issue by AxteriaFX** [FixedDev/EzChat#3]
[13:34:12] [Server thread/INFO]: [EzChat] Enabling EzChat v2.5.0*
[13:34:12] [Server thread/INFO]: [EzChat] Downloading dependencies
[13:34:18] [Server thread/INFO]: [EzChat] Dependencies downloaded successfully!
[13:34:18] [Server thread/ERROR]: Error occurred while enabling EzChat v2.5.0 (Is it up to date?)
[13:34:18] [Server thread/ERROR]: Suspected Plugins: 
[13:34:18] [Server thread/ERROR]: 	EzChat{enabled,ver=2.5.0,path=plugins\EzChat-2.5.0.jar}
[13:34:18] [Server thread/ERROR]: Exception details below: 
java.lang.NoClassDefFoundError: me/fixeddev/ezchat/commandflow/annotated/CommandClass
	at me.fixeddev.ezchat.ChatPlugin.registerCommands(ChatPlugin.java:90) ~[?:?]
	at me.fixeddev.ezchat.ChatPlugin.onEnable(ChatPlugin.java:62) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: me.fixeddev.ezchat.commandflow.annotated.CommandClass
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 12 more
[13:34:18] [Server thread/INFO]: [EzChat] Disabling EzChat v2.5.0
[13:34:18] [Server thread/ERROR]: Error occurred while disabling EzChat v2.5.0 (Is it up to date?)
[13:34:18] [Server thread/ERROR]: Suspected Plugins: 
[13:34:18] [Server thread/ERROR]: 	EzChat{disabled,ver=2.5.0,path=plugins\EzChat-2.5.0.jar}
[13:34:18] [Server thread/ERROR]: Exception details below: 
java.lang.NullPointerException: null
	at me.fixeddev.ezchat.ChatPlugin.onDisable(ChatPlugin.java:45) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:419) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:388) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:303) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-114]
	at java.lang.Thread.run(Unknown Source) [?:?]
	
	don't install all dependencies

**Comment by FixedDev** [comment]
Fixed.
